# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v3
        with:
          node-version: 21.2.0

      - uses: actions/checkout@v3

      - run: ls

      - run: npm run build

      - run: cd out

      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
